sudo: false

language: go

os:
  - linux
  - osx

go:
  - tip
  - 1.12.x
  - 1.13

script:
  - GO111MODULE=on go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - GO111MODULE=on go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

script:
  - test -z "$(gofmt -s -l . | tee /dev/stderr)"
  - go test -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always
