name: Testing

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    # We want to run on external PRs, but not on our own internal
    # PRs as they'll be run by the push to the branch.
    #
    # The main trick is described here:
    # https://github.com/Dart-Code/Dart-Code/pull/2375
    if: github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Clone repository with source code
        uses: actions/checkout@v2

      - name: Check Golang code style
        run: |
          diff -u <(echo -n) <(gofmt -d -s .)
          test -z "$(gofmt -s -l . | tee /dev/stderr)"

      - name: Run tests
        run: |
          GO111MODULE=on go get -t -v ./...
          go test -v ./...
